ExamenAgil/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView #, logout_then_login
# from django.contrib.auth.decorators import login_required
# from django.conf import settings
# from django.contrib.auth import views as views_auth
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.login, name="login"),
    path('index', views.home, name="index"),
    path('login', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('signup/arrendatario', views.SignupUserArrendatario.as_view(), name="signup_arrendatario"),
    path('signup/arrendador', views.SignupUserArrendador.as_view(), name="signup_arrendador"),
    path('profile/', views.ProfileUpdate.as_view(), name="profile"),
    path('profile/credit-card', views.CreditCardUpdate.as_view(), name="credit-card"),
    path('parking', views.ParkingList.as_view(), name="parking_list"),
    path('parking/new', views.ParkingCreate.as_view(), name="parking_new"),
    path('parking/<int:pk>', views.ParkingUpdate.as_view(), name="parking_update"),
    path('parking/<int:pk>/delete', views.ParkingDelete.as_view(), name="parking_delete"),
    path('rent', views.rent, name="rent"),

    # path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    # path('logout/', views_auth.logout_then_login, {'login_url': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    # path('registro/', RegistroUsuario.as_view(), name="registro"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

PROFILE_SEXOS = (
    ('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'), 
)

CREDITCARD_TIPOS = (
    ('VISA', 'VISA'),
    ('MASTERCARD', 'MASTERCARD'),   
)

PARKINGRENT_ESTADOS = (
    ('RENT', 'En eenta'),
    ('END', 'Finalizado'),
    ('CANCELED', 'Cancelado'),
    ('PENDING', 'Pago pendiente'),
    ('PAID', 'Pagado'),
)

class Profile(models.Model):
    nombre = models.CharField(max_length=80, null=True, blank=True)
    direccion = models.CharField(max_length=100, null=True, blank=True)
    ciudad = models.CharField(max_length=100, null=True, blank=True)
    celular = models.IntegerField(null=True, blank=True)
    sexo = models.CharField(max_length=30, choices=PROFILE_SEXOS, null=True, blank=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.nombre is None:
            return self.usuario.username
        else:
            return self.nombre

class CreditCard(models.Model):
    tipo = models.CharField(max_length=20, choices=CREDITCARD_TIPOS, null=True)
    nombre = models.CharField(max_length=80, null=True)
    numero = models.IntegerField(null=True)
    fechaVencimiento = models.DateField(null=True)
    cvv = models.IntegerField(null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.numero is None:
            return self.usuario.username
        else:
            return str(self.numero)

class Parking(models.Model):
    direccion = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=80)
    pais = models.CharField(max_length=80)
    geo_x = models.FloatField()
    geo_y = models.FloatField()
    valor = models.IntegerField()
    propietario = models.ForeignKey(User, on_delete=models.CASCADE)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.direccion + ', ' + self.ciudad + ', ' + self.pais + '.'

class ParkingRent(models.Model):
    arrendador = models.ForeignKey(User, on_delete=models.CASCADE)
    arrendatario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="arrendatario")
    fecha = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=20, choices=PARKINGRENT_ESTADOS, default="RENT")
    duracion = models.IntegerField(null=True, blank=True)
    valor = models.IntegerField(null=True, blank=True)
    parking = models.ForeignKey(Parking, on_delete=models.CASCADE)

    def __str__(self):
        return self.arrendatario.username + ' ' + str(self.fecha) + ' - ' + self.estado


# Recivers

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(usuario=instance)
        CreditCard.objects.create(usuario=instance)

core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile, CreditCard, Parking, PROFILE_SEXOS, CREDITCARD_TIPOS, ParkingRent

class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = {
            'username',
            'email',
            'password1',
            'password2',
            }
        labels = {
            'username':'Nombre de Usuario',
            'email':'Email',
            'password1':'Contraseña',
            'password2':'Repita Contraseña',
            }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['usuario']
        widgets = {
            'nombre' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'direccion' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'ciudad' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'celular' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'sexo' : forms.Select(attrs={'class':'form-control'}, choices=PROFILE_SEXOS),
        }

class CreditCardForm(forms.ModelForm):
    class Meta:
        model = CreditCard
        fields = '__all__'
        exclude = ['usuario']
        widgets = {
            'nombre' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'numero' : forms.NumberInput(attrs={'type': 'text','class':'form-control'}),
            'cvv' : forms.TextInput(attrs={'type': 'text','class':'form-control','maxlength':'3'}),
            'tipo' : forms.Select(attrs={'class':'form-control','placeholder':'MM/YY'}, choices=CREDITCARD_TIPOS),
        }

class ParkingForm(forms.ModelForm):
    geo_x = forms.CharField(required=False)
    geo_y = forms.CharField(required=False)

    class Meta:
        model = Parking
        fields = '__all__'
        exclude = ['propietario', 'disponible']
        widgets = {
            'direccion' : forms.TextInput(attrs={'type': 'text','class':'form-control','placeholder':'Calle Nº'}),
            'ciudad' : forms.NumberInput(attrs={'type': 'text','class':'form-control','value':'Santiago'}),
            'pais' : forms.TextInput(attrs={'type': 'text','class':'form-control','value':'Chile'}),
            'valor' : forms.NumberInput(attrs={'type': 'number','class':'form-control'}),
        }

class RentForm(forms.ModelForm):
    class Meta:
        model = ParkingRent
        fields = ['estado']

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from .forms import SignupForm, ProfileForm, CreditCardForm, ParkingForm, RentForm
from .models import Profile, CreditCard, Parking, ParkingRent
from .decorators import group_required

# Create your views here.

@login_required
def home(request):
    group = request.user.groups.filter(name='Arrendatario').exists()
    if group:
        return redirect('core:rent')
    else:
        return redirect('core:parking_list')

def login(request):
    return render(request, 'core/login.html')

class SignupUserArrendatario(LoginRequiredMixin, CreateView):
    model = get_user_model()
    template_name = "core/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy('core:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['role']='Arrendatario'
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.groups.add(Group.objects.get(name='Arrendatario'))
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class SignupUserArrendador(CreateView):
    model = get_user_model()
    template_name = "core/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy('core:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['role']='Arrendador'
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.groups.add(Group.objects.get(name='Arrendador'))
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class ProfileUpdate(UpdateView):
    model = Profile
    template_name = "core/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy('core:profile')

    def get_object(self):
        return Profile.objects.get(usuario=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creditCard']=CreditCard.objects.get(usuario=self.request.user)
        return context

class CreditCardUpdate(UpdateView):
    model = CreditCard
    template_name = "core/credit-card.html"
    form_class = CreditCardForm
    success_url = reverse_lazy('core:profile')

    def get_object(self):
        return CreditCard.objects.get(usuario=self.request.user)
    
    def post(self, request, **kwargs):
        request.POST = request.POST.copy()
        request.POST['fechaVencimiento'] = "01/" + request.POST['fechaVencimiento']
        return super(CreditCardUpdate, self).post(request, **kwargs)

class ParkingList(ListView):
    model = Parking
    template_name = "core/parking_list.html"
    context_object_name = "parkings"

    def get_queryset(self):
        return Parking.objects.filter(propietario=self.request.user)

class ParkingCreate(CreateView):
    model = Parking
    template_name = "core/parking_form.html"
    form_class = ParkingForm
    success_url = reverse_lazy('core:parking_new')
    
    def form_valid(self, form):
        form.instance.propietario = self.request.user
        return super(ParkingCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creditCard']=CreditCard.objects.get(usuario=self.request.user)
        return context


class ParkingUpdate(UpdateView):
    model = Parking
    template_name = "core/parking_update.html"
    context_object_name = 'parking'
    form_class = ParkingForm
    success_url = reverse_lazy('core:parking_list')

class ParkingDelete(DeleteView):
    model = Parking
    template_name = "core/parking_delete.html"
    context_object_name = 'parking'
    success_url = reverse_lazy('core:parking_list')

class Rent(CreateView):
    model = ParkingRent
    template_name = "core/home.html"
    # form_class = RentForm
    success_url = reverse_lazy('core:login')

    def get_queryset(self):
        return ParkingRent.objects.filter(propietario=self.request.user, )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rent']=ParkingRent.objects.get(arrendatario=self.request.user)
        return context

@login_required
def rent(request):
    rents = ParkingRent.objects.filter(arrendatario=request.user)
    parkings = Parking.objects.filter(disponible=True)
    creditCard = CreditCard.objects.filter(usuario=request.user)

    if request.POST:
        if request.POST.get('parking', None) != None:
            parking = Parking.objects.get(pk=request.POST['parking'])
            rent = ParkingRent()
            rent.parking = parking
            rent.arrendador = parking.propietario
            rent.arrendatario = request.user
            rent.save()
            parking.disponible = False
            parking.save()

        if request.POST.get('remove', None) != None:
            rent = ParkingRent.objects.get(pk=request.POST['remove'])
            parking = Parking.objects.get(pk=rent.parking.pk)
            diff = timezone.now() - rent.fecha
            mins = round(diff.days * 1440 + diff.seconds/60)
            rent.valor = 0
            rent.duracion = mins
            rent.estado = "CANCELED"
            rent.save()            
            parking.disponible = True
            parking.save()

        if request.POST.get('payment', None) != None:
            rent = ParkingRent.objects.get(pk=request.POST['payment'])
            parking = Parking.objects.get(pk=rent.parking.pk)
            diff = timezone.now() - rent.fecha
            mins = round(diff.days * 1440 + diff.seconds/60)
            cost = mins * parking.valor
            rent.valor = cost
            rent.duracion = mins
            rent.estado = "PAID"
            rent.save()
            parking.disponible = True
            parking.save()

    context = {
        'rents': rents,
        'parkings': parkings,
        'creditCard': creditCard
    }
    return render(request, 'core/home.html', context)

core/templates/core/login.html
<style type="text/css">
    body { background: linear-gradient(141deg, #e1bee7 0%, #9c27b0 51%, #7b1fa2 75%) !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

{% extends 'base/base.html' %}
{% load staticfiles %}

{% block navbar %}
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center pt-5">
  <div class="col-lg-4 col-sm-8 col-xs-3 jumbotron">
    <div>
      <h3 class="font-italic text-center"><strong class="text-primary">Mi</strong> Estacionamiento</h3>
      <hr>
      <h3 class="pb-3">Login</h3>

      <!-- FORMULARIO -->
      <form method="POST" id="loginForm">
        {% csrf_token %}

        <div class="form-group">
          <label for="username">Nombre de Usuario</label><br>
          <input name="username" class="form-control" type="text"/>
        </div>

        <div class="form-group">
          <label for="password">Contraseña</label><br>
          <input name="password" class="form-control" type="password"/>
        </div>

        {% if form.errors %}
        <div class="form-group">
          <div class="bg-danger mt-1 p-2">Nombre de usuario o contraseña incorrecto.</div>
        </div>  
        {% endif %}             

        <div class="form-group text-center">
          <input class="btn btn-secondary" type="submit" value="Iniciar sesión"/>
        </div>
        
      </form>
      <!-- FIN FORMULARIO-->

      <p class="text-muted pt-2">Aun no tienes cuenta?
        <a href="{% url 'core:signup_arrendatario' %}">Resgistrarse</a>
      </p>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

core/templates/core/parking_delete.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %}
<style>
  #map {
    height: 100%;
    padding-top: 50px !important;
  }
</style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2 class="display-5 text-light bg-dark p-3 text-center text-lg-left rounded">Mis Estacionamientos</h2>
    <br>

    <div class="row">
    <div class="col-lg-12">
      <h3 class="text-center text-sm-left">Eliminar</h3>
      
      <br>
      <!-- FORMULARIO DATOS BANCARIOS-->
      <form method="POST" id="parkingDelteForm">
        {% csrf_token %}

        <div class="form-group">
          <h4>¿Deseas eliminar el estacionamiento de la dirección {{parking}}?</h4>
          <i class="text-muted">*Este registro no se podra recuperar.</i>
        </div>

        <br>

        <div class="text-lg-left text-center">
          <div class="form-group">
            <input class="btn btn-danger mr-2" type="submit" value="Eliminar"/>
            <a class="btn" href="{% url 'core:parking_list' %}">Cancelar</a>
          </div>
        </div>

        {% if form.errors %}
        {{ form.errors }}
        {% endif %}

      </form>
      <!-- FIN FORMULARIO-->
    </div>
  </div>

  </div>

</div>
<br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

core/templates/core/parking_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %}
<style>
    .dot {
        height: 18px;
        width: 18px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
    }
</style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2 class="display-5 text-light bg-dark p-3 text-center text-lg-left rounded">Estacionamientos registrados</h2>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Dirección</th>
                <th scope="col">Valor ($)</th>
                <th scope="col">Disponible</th>
            </tr>
        </thead>
        <tbody>
            {% for parking in parkings %}
            <tr scope="row" onclick="redirect('{{parking.pk}}')">
                <th><a href="{% url 'core:parking_update' parking.pk %}"><i class="material-icons text-info" style="font-size: 20px">edit</i></a> | {{ forloop.counter }}</th>    
                <th>{{parking}}</th>                 
                <th>{{parking.valor}}</th> 
                <th>
                    <span class="dot"
                        {% if parking.disponible %} style="background-color: green"
                        {% else%} style="background-color: red"
                        {% endif %}>
                    </span>
                </th>     
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>

  <!-- LISTA -->
  <br><br><br><br><br><br><br><br><br><br><br><br>
  <br><br><br><br><br><br><br><br><br><br><br><br>
  
  <!-- FIN LISTA-->

</div>
{% endblock %}

core/templates/core/parking_update.html
{% extends 'base/base.html' %}
{% load static %}

{% block head %}
<style>
  #map {
    height: 100%;
    padding-top: 50px !important;
  }
</style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2 class="display-5 text-light bg-dark p-3 text-center text-lg-left rounded">Mis Estacionamientos</h2>
    <br>

    <div class="row">
    <div class="col-lg-6">
      <h3 class="text-center text-sm-left">Editar <a href="{% url 'core:parking_delete' parking.pk %}" class="color-danger" style="font-size: 12px">(Eliminar)</a></h3>
      
      <br>
      <!-- FORMULARIO DATOS BANCARIOS-->
      <form method="POST" id="parkingUpdateForm">
        {% csrf_token %}

        <div class="form-group">
          <label for="tipo" class="bmd-label-floating">Dirección</label>
          {{ form.direccion }}
        </div>

        <div class="form-group">
          <label for="ciudad" class="bmd-label-floating">Ciudad</label>
          {{ form.ciudad }}
        </div>

        <div class="form-group">
          <label for="pais" class="bmd-label-floating">País</label>
          {{ form.pais }}
        </div>

        <div class="form-group">
          <label for="valor">Valor por minuto ($)</label>
          {{ form.valor }}
        </div>

        <div class="form-group d-none">
          <label for="geo_x">Valor por minuto ($)</label>
          {{ form.geo_x }}
        </div>

        <div class="form-group d-none">
          <label for="geo_y">Valor por minuto ($)</label>
          {{ form.geo_y }}
        </div>

        <br><br>

        <p class="bg-info p-2" style="border-radius: 8px" id="info_text">*Marca la localización en el mapa.</p>

        <div class="text-lg-left text-center">
          <div class="form-group">
            <input class="btn btn-primary mr-2" type="submit" value="Guardar" id="btn_submit" disabled/>
            <a class="btn" href="{% url 'core:parking_list' %}">Cancelar</a>
          </div>
        </div>

        {% if form.errors %}
        {{ form.errors }}
        {% endif %}

      </form>
      <!-- FIN FORMULARIO-->
    </div>
  </div>

  </div>
  <div class="col-lg-6">
    <!-- <h2 class="display-5 text-light bg-dark p-3 text-center text-lg-left rounded">Mis Estacionamientos</h2> -->
    <br><br><br><br>
      
    <div id="map"></div>

    

  </div>

</div>
<br><br><br><br><br><br><br>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  var geo_x;
  var geo_y;
  var map;
  
  function getLocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(setPosition);
    } else {
      alert('Geolocalización no disponible.');
    }
  }

  function setPosition(position) {
    geo_x = position.coords.latitude;
    geo_y = position.coords.longitude;
    initMap()
  }

  function initMap() {
    // Map
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: geo_x, lng: geo_y},
      zoom: 17
    });
    var marker = new google.maps.Marker({
      position: {lat: geo_x, lng: geo_y},
      map: map,
	    title: 'Pocición actual',
      animation:google.maps.Animation.BOUNCE
    });

    // Marks
    var icon = '{% static "icons/parking.icon.png" %}'
    var parking;

    google.maps.event.addListener(map, 'click', function(event) {
      placeMarker(map, event.latLng);
    });

    function placeMarker(map, location) {
      var btn = document.getElementById('btn_submit');
      if (btn.disabled) {
        btn.disabled = false
        var element = document.getElementById('info_text');
        element.parentNode.removeChild(element);
      }
      
      if (parking !== undefined){
        parking.setMap(null);
      }
      parking = new google.maps.Marker({
        position: location,
        map: map,
        icon: icon,
      });
      document.getElementById('id_geo_x').value = location.lat();
      document.getElementById('id_geo_y').value = location.lng();
      console.log(document.getElementById('id_geo_x').value, document.getElementById('id_geo_y').value)
    }
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCVDb1W19mfeEnn4UQhpRaRrsReu8UOA6Y&callback=getLocation" async defer></script>
{% endblock %}

core/templates/core/profile.html
{% extends 'base/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h2 class="display-5 text-light bg-dark p-3 text-center text-lg-left rounded">Perfil</h2>
    <br>

    <div class="row">
    <div class="col-lg-6 mb-3">
      <h3 class="text-center text-sm-left">Datos personales</h3>
      <br>
      <!-- FORMULARIO DATOS PERSONALES-->
      <form method="POST" id="profileForm">
        {% csrf_token %}
        <div class="form-group">
          <label for="nombre" class="bmd-label-floating">Nombre Completo</label>
          <input name="nombre" id="name" class="form-control" type="text" {% if form.nombre.value != None %}value="{{form.nombre.value}}"{% endif %} maxlength="80"/>
        </div>

        <div class="form-group">
          <label for="direccion">Dirección</label><br>
          {{form.direccion}}
        </div>

        <div class="form-group">
          <label for="ciudad">Ciudad</label><br>
          {{form.ciudad}}
        </div>

        <div class="form-group">
          <label for="celular">Número de Teléfono</label><br>
          {{form.celular}}
        </div>

        <div class="form-group">
          <label for="sexo">Sexo</label><br>
          {{form.sexo}}
        </div>

        <div class="text-lg-left text-center">
          <div class="form-group">
            <input class="btn btn-primary" type="submit" value="Guardar"/>
          </div>
        </div>

      </form>
      <!-- FIN FORMULARIO-->
    </div>
    
  
    <div class="col-lg-6">
      <h3 class="text-center text-sm-left">
        Datos bancarios <a class="d-md-inline d-none" href="{% url 'core:credit-card' %}" style="font-size: 14px">(editar)</a>
      </h3>
      <div class="d-md-none d-xs-block text-center">
        <a href="{% url 'core:credit-card' %}" style="font-size: 14px">(editar)</a>
      </div>
      <br>
      <!-- FORMULARIO DATOS BANCARIOS-->
      <form method="POST" id="creaditCardForm">
        {% csrf_token %}

        {% if creditCard.numero != None %}
        <div class="form-group">
          <label for="tipo" class="bmd-label-floating">Tarjeta</label>
          <select name="tipo" id="tipo" class="form-control" disabled>
            <option>{{creditCard.tipo}}</option>
          </select>
        </div>

        <div class="form-group">
          <label for="nombre" class="bmd-label-floating">Nombre</label>
          <input value="{{creditCard.nombre}}" name="nombre" class="form-control" type="text" readonly/>
        </div>
        <div class="form-group">
          <label for="numero">Número</label>
          <input value="{{creditCard.numero}}" name="numero" id="numero" class="form-control" type="text" readonly/>
        </div>
        <div class="row">
          <div class="col-lg-6 form-group">
            <label for="fecha">Fecha de vencimiento</label><br>
            <input value="{{creditCard.fechaVencimiento|date:'m/y'}}" name="fecha" class="form-control" type="text" readonly/>
          </div>
          <div class="col-lg-6 form-group">
            <label for="cvv">cvv</label><br>
            <input value="{{creditCard.cvv}}" name="cvv" class="form-control" type="text" readonly/>
          </div>            
        </div>
        {% else %}
        <p>Aun no se ha ingreaso una Tarjeta de Credito.</p>
        {% endif %}

      </form>
      <!-- FIN FORMULARIO-->
    </div>

  </div>

  </div>
</div>
{% endblock %}

core/templates/core/signup.html
<style type="text/css">
    body { background: linear-gradient(141deg, #e1bee7 0%, #9c27b0 51%, #7b1fa2 75%) !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>

{% extends 'base/base.html' %}
{% load staticfiles %}

{% block navbar %}
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center pt-5 pb-5">
  <div class="col-lg-4 col-sm-8 col-xs-3 jumbotron">
    <div>
      <h3 class="font-italic text-center"><strong class="text-primary">Mi</strong> Estacionamiento</h3>
      <hr>
      <h3 class="pb-3">Registro como {{ role }} </h3>

      <!-- FORMULARIO -->      
      <form method="POST" id="formulario">
        {% csrf_token %}

        <div class="form-group">
            <label for="username">Nombre de Usuario</label><br>
            <input name="username" class="form-control" type="text"/>
        </div>

        <div class="form-group">
            <label for="email">Email</label><br>
            <input name="email" class="form-control" type="text"/>
        </div>

        <div class="form-group">
            <label for="password1">Contraseña</label><br>
            <input name="password1" class="form-control" type="password"/>
        </div>

        <div class="form-group">
            <label for="password2">Repetir Contraseña</label><br>
            <input name="password2" class="form-control" type="password"/>
        </div>

        <div class="form-group">
          <i class="text-muted">*La contraseña debe tener como minimo 8 carácteres, una letra y un número, sin carácteres especiales($,&,@, etc..).</i>
        </div>
        {% if form.errors %}
        <div class="form-group">
          <div class="bg-danger mt-1 p-2 text-light">Error, intente nuevamente.</div>
        </div>  
        {% endif %}

        <div class="form-group text-center">
          <input class="btn btn-secondary" type="submit" value="Registrarse"/>
        </div>

      <!-- FIN FORMULARIO-->

      <p class="pt-2">
        <a href="{% url 'core:login' %}" class="text-muted"><i class="material-icons">arrow_left</i>Login</a>
        <br>
        {% if role == 'Arrendatario' %}
        <a href="{% url 'core:signup_arrendador' %}" class="pl-4">registrarse como arrendador</a>
        {% else %}
        <a href="{% url 'core:signup_arrendatario' %}" class="pl-4">registrarse como arrendatario</a>
        {% endif %}
      </p>
    </div>
  </div>
</div>
{% endblock %}

{% block footer %}
{% endblock %}