ExamenAgil/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView #, logout_then_login
# from django.contrib.auth.decorators import login_required
# from django.conf import settings
# from django.contrib.auth import views as views_auth
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.login, name="login"),
    path('index', views.home, name="index"),
    path('login', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('signup/arrendatario', views.SignupUserArrendatario.as_view(), name="signup_arrendatario"),
    path('signup/arrendador', views.SignupUserArrendador.as_view(), name="signup_arrendador"),
    path('profile/', views.ProfileUpdate.as_view(), name="profile"),
    path('profile/credit-card', views.CreditCardUpdate.as_view(), name="credit-card"),
    path('parking', views.ParkingList.as_view(), name="parking_list"),
    path('parking/new', views.ParkingCreate.as_view(), name="parking_new"),
    path('parking/<int:pk>', views.ParkingUpdate.as_view(), name="parking_update"),
    path('parking/<int:pk>/delete', views.ParkingDelete.as_view(), name="parking_delete"),
    path('rent', views.rent, name="rent"),

    # path('login/', LoginView.as_view(template_name='login.html'), name="login"),
    # path('logout/', views_auth.logout_then_login, {'login_url': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    # path('registro/', RegistroUsuario.as_view(), name="registro"),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

PROFILE_SEXOS = (
    ('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'), 
)

CREDITCARD_TIPOS = (
    ('VISA', 'VISA'),
    ('MASTERCARD', 'MASTERCARD'),   
)

PARKINGRENT_ESTADOS = (
    ('RENT', 'En eenta'),
    ('END', 'Finalizado'),
    ('CANCELED', 'Cancelado'),
    ('PENDING', 'Pago pendiente'),
    ('PAID', 'Pagado'),
)

class Profile(models.Model):
    nombre = models.CharField(max_length=80, null=True, blank=True)
    direccion = models.CharField(max_length=100, null=True, blank=True)
    ciudad = models.CharField(max_length=100, null=True, blank=True)
    celular = models.IntegerField(null=True, blank=True)
    sexo = models.CharField(max_length=30, choices=PROFILE_SEXOS, null=True, blank=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.nombre is None:
            return self.usuario.username
        else:
            return self.nombre

class CreditCard(models.Model):
    tipo = models.CharField(max_length=20, choices=CREDITCARD_TIPOS, null=True)
    nombre = models.CharField(max_length=80, null=True)
    numero = models.IntegerField(null=True)
    fechaVencimiento = models.DateField(null=True)
    cvv = models.IntegerField(null=True)
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.numero is None:
            return self.usuario.username
        else:
            return str(self.numero)

class Parking(models.Model):
    direccion = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=80)
    pais = models.CharField(max_length=80)
    geo_x = models.FloatField()
    geo_y = models.FloatField()
    valor = models.IntegerField()
    propietario = models.ForeignKey(User, on_delete=models.CASCADE)
    disponible = models.BooleanField(default=True)

    def __str__(self):
        return self.direccion + ', ' + self.ciudad + ', ' + self.pais + '.'

class ParkingRent(models.Model):
    arrendador = models.ForeignKey(User, on_delete=models.CASCADE)
    arrendatario = models.ForeignKey(User, on_delete=models.CASCADE, related_name="arrendatario")
    fecha = models.DateTimeField(auto_now=True)
    estado = models.CharField(max_length=20, choices=PARKINGRENT_ESTADOS, default="RENT")
    duracion = models.IntegerField(null=True, blank=True)
    valor = models.IntegerField(null=True, blank=True)
    parking = models.ForeignKey(Parking, on_delete=models.CASCADE)

    def __str__(self):
        return self.arrendatario.username + ' ' + str(self.fecha) + ' - ' + self.estado


# Recivers

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(usuario=instance)
        CreditCard.objects.create(usuario=instance)

core/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Profile, CreditCard, Parking, PROFILE_SEXOS, CREDITCARD_TIPOS, ParkingRent

class SignupForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = {
            'username',
            'email',
            'password1',
            'password2',
            }
        labels = {
            'username':'Nombre de Usuario',
            'email':'Email',
            'password1':'Contraseña',
            'password2':'Repita Contraseña',
            }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['usuario']
        widgets = {
            'nombre' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'direccion' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'ciudad' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'celular' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'sexo' : forms.Select(attrs={'class':'form-control'}, choices=PROFILE_SEXOS),
        }

class CreditCardForm(forms.ModelForm):
    class Meta:
        model = CreditCard
        fields = '__all__'
        exclude = ['usuario']
        widgets = {
            'nombre' : forms.TextInput(attrs={'type': 'text','class':'form-control'}),
            'numero' : forms.NumberInput(attrs={'type': 'text','class':'form-control'}),
            'cvv' : forms.TextInput(attrs={'type': 'text','class':'form-control','maxlength':'3'}),
            'tipo' : forms.Select(attrs={'class':'form-control','placeholder':'MM/YY'}, choices=CREDITCARD_TIPOS),
        }

class ParkingForm(forms.ModelForm):
    geo_x = forms.CharField(required=False)
    geo_y = forms.CharField(required=False)

    class Meta:
        model = Parking
        fields = '__all__'
        exclude = ['propietario', 'disponible']
        widgets = {
            'direccion' : forms.TextInput(attrs={'type': 'text','class':'form-control','placeholder':'Calle Nº'}),
            'ciudad' : forms.NumberInput(attrs={'type': 'text','class':'form-control','value':'Santiago'}),
            'pais' : forms.TextInput(attrs={'type': 'text','class':'form-control','value':'Chile'}),
            'valor' : forms.NumberInput(attrs={'type': 'number','class':'form-control'}),
        }

class RentForm(forms.ModelForm):
    class Meta:
        model = ParkingRent
        fields = ['estado']

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.urls import reverse_lazy
from .forms import SignupForm, ProfileForm, CreditCardForm, ParkingForm, RentForm
from .models import Profile, CreditCard, Parking, ParkingRent
from .decorators import group_required

# Create your views here.

@login_required
def home(request):
    group = request.user.groups.filter(name='Arrendatario').exists()
    if group:
        return redirect('core:rent')
    else:
        return redirect('core:parking_list')

def login(request):
    return render(request, 'core/login.html')

class SignupUserArrendatario(LoginRequiredMixin, CreateView):
    model = get_user_model()
    template_name = "core/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy('core:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['role']='Arrendatario'
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.groups.add(Group.objects.get(name='Arrendatario'))
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class SignupUserArrendador(CreateView):
    model = get_user_model()
    template_name = "core/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy('core:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['role']='Arrendador'
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.groups.add(Group.objects.get(name='Arrendador'))
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class ProfileUpdate(UpdateView):
    model = Profile
    template_name = "core/profile.html"
    form_class = ProfileForm
    success_url = reverse_lazy('core:profile')

    def get_object(self):
        return Profile.objects.get(usuario=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creditCard']=CreditCard.objects.get(usuario=self.request.user)
        return context

class CreditCardUpdate(UpdateView):
    model = CreditCard
    template_name = "core/credit-card.html"
    form_class = CreditCardForm
    success_url = reverse_lazy('core:profile')

    def get_object(self):
        return CreditCard.objects.get(usuario=self.request.user)
    
    def post(self, request, **kwargs):
        request.POST = request.POST.copy()
        request.POST['fechaVencimiento'] = "01/" + request.POST['fechaVencimiento']
        return super(CreditCardUpdate, self).post(request, **kwargs)

class ParkingList(ListView):
    model = Parking
    template_name = "core/parking_list.html"
    context_object_name = "parkings"

    def get_queryset(self):
        return Parking.objects.filter(propietario=self.request.user)

class ParkingCreate(CreateView):
    model = Parking
    template_name = "core/parking_form.html"
    form_class = ParkingForm
    success_url = reverse_lazy('core:parking_new')
    
    def form_valid(self, form):
        form.instance.propietario = self.request.user
        return super(ParkingCreate, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creditCard']=CreditCard.objects.get(usuario=self.request.user)
        return context


class ParkingUpdate(UpdateView):
    model = Parking
    template_name = "core/parking_update.html"
    context_object_name = 'parking'
    form_class = ParkingForm
    success_url = reverse_lazy('core:parking_list')

class ParkingDelete(DeleteView):
    model = Parking
    template_name = "core/parking_delete.html"
    context_object_name = 'parking'
    success_url = reverse_lazy('core:parking_list')

class Rent(CreateView):
    model = ParkingRent
    template_name = "core/home.html"
    # form_class = RentForm
    success_url = reverse_lazy('core:login')

    def get_queryset(self):
        return ParkingRent.objects.filter(propietario=self.request.user, )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rent']=ParkingRent.objects.get(arrendatario=self.request.user)
        return context

@login_required
def rent(request):
    rents = ParkingRent.objects.filter(arrendatario=request.user)
    parkings = Parking.objects.filter(disponible=True)
    creditCard = CreditCard.objects.filter(usuario=request.user)

    if request.POST:
        if request.POST.get('parking', None) != None:
            parking = Parking.objects.get(pk=request.POST['parking'])
            rent = ParkingRent()
            rent.parking = parking
            rent.arrendador = parking.propietario
            rent.arrendatario = request.user
            rent.save()
            parking.disponible = False
            parking.save()

        if request.POST.get('remove', None) != None:
            rent = ParkingRent.objects.get(pk=request.POST['remove'])
            parking = Parking.objects.get(pk=rent.parking.pk)
            diff = timezone.now() - rent.fecha
            mins = round(diff.days * 1440 + diff.seconds/60)
            rent.valor = 0
            rent.duracion = mins
            rent.estado = "CANCELED"
            rent.save()            
            parking.disponible = True
            parking.save()

        if request.POST.get('payment', None) != None:
            rent = ParkingRent.objects.get(pk=request.POST['payment'])
            parking = Parking.objects.get(pk=rent.parking.pk)
            diff = timezone.now() - rent.fecha
            mins = round(diff.days * 1440 + diff.seconds/60)
            cost = mins * parking.valor
            rent.valor = cost
            rent.duracion = mins
            rent.estado = "PAID"
            rent.save()
            parking.disponible = True
            parking.save()

    context = {
        'rents': rents,
        'parkings': parkings,
        'creditCard': creditCard
    }
    return render(request, 'core/home.html', context)

core/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <!-- Titulo -->
    <title>Mi Estacionamiento - {% block title %}  {% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Estilos -->
    <link rel="stylesheet" href="{% static 'css/material.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- <link rel="stylesheet" href="{% static 'css/estilos.css' %}"> -->
    {% block head %}
    {% endblock %}

</head>
<body>
<div>      
    {% block navbar %}
    <!-- Cabezera -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand mb-0 h1" href="{% url 'core:index' %}">
            <span class="font-italic"><strong class="text-primary">Mi</strong> Estacionamiento</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navegacion" aria-controls="navegacion" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navegacion">
            <ul class="navbar-nav">            
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'core:index' %}">Inicio</a>
                </li>
                {% ifequal user.groups.all.0.name 'Arrendador' %}
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'core:parking_new' %}">Agregar</a>
                </li>
                {% endifequal %}
            </ul>
            <ul class="navbar-nav flex-row ml-lg-auto d-none d-lg-flex">
                <li class="nav-item">
                    <span class="nav-link">({{ user }})</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:profile' %}">Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="d-xs-none navbar-brand ml-2" href="{% url 'core:login' %}"><i class="material-icons">exit_to_app</i></a>
                </li>
                {% comment %} <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Perfil</a>
                    <div class="dropdown-menu" x-placement="bottom-start" >
                    <a class="dropdown-item" href="#">Cerrar Sesión</a>
                </li> {% endcomment %}
            </ul>
        </div>
    </nav>
    {% endblock %}

    {% block header %}
    {% endblock %}

    <div  class="container-fluid mt-3">
    {% block content %}
    {% endblock %}
    </div>

    {% block footer %}
    <!-- Pie de página -->
    <br><br><br>
    <footer id="footer" class="footer bg-dark pt-lg-5 pt-2">
        <div class="d-none d-lg-flex justify-content-center p-2">
            <p class="text-light text-justify">
                Gestión Agil de Proyectos || Robinson Humé, Camilo Lucero, Nicolás Leporati || 2019 DuocUC || <a href="/admin">Administración</a>
            </p>
        </div>
        <div class="d-lg-none p-2">
            <span class="text-light text-center">
                <p>Gestión Agil de Proyectos</p>
                <p>Robinson Humé, Camilo Lucero, Nicolás Leporati</p>
                <p>2019 DuocUC</p>
                <p><a href="/admin">Administración</a></p>
            </span>
        </div>
    </footer>
    {% endblock %}    

</div>

    <!-- Scripts -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/material.js' %}"></script>
    {% block extrajs %}
    {% endblock %}

</body>
</html>